-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


CREATE TABLE EMPLOYEES (
    Emp_No INT   NOT NULL,
    Birth_Date DATE   NOT NULL,
    First_Name VARCHAR   NOT NULL,
    Last_Name VARCHAR   NOT NULL,
    Gender VARCHAR(10)   NOT NULL,
    Hire_Date DATE   NOT NULL,
    CONSTRAINT pk_EMPLOYEES PRIMARY KEY (
        Emp_No
     )
);

CREATE TABLE SALARIES (
    Emp_No INT   NOT NULL,
    Salary INT   NOT NULL,
    From_Date DATE   NOT NULL,
    To_Date DATE   NOT NULL
);

CREATE TABLE TITLES (
    Emp_No INT   NOT NULL,
    Title VARCHAR   NOT NULL,
    From_Date DATE   NOT NULL,
    To_Date DATE   NOT NULL
);

CREATE TABLE DEPARTMENTS (
    Dept_No VARCHAR(10)   NOT NULL,
    Dept_Name VARCHAR   NOT NULL,
    CONSTRAINT pk_DEPARTMENTS PRIMARY KEY (
        Dept_No
     )
);

CREATE TABLE DEPT_MANAGER (
    Dept_No VARCHAR(10)   NOT NULL,
    Emp_No INT   NOT NULL,
    From_Date DATE   NOT NULL,
    To_Date DATE   NOT NULL
);

CREATE TABLE DEPT_EMP (
    Emp_No INT   NOT NULL,
    Dept_No VARCHAR(10)   NOT NULL,
    From_Date DATE   NOT NULL,
    To_Date DATE   NOT NULL
);

ALTER TABLE SALARIES ADD CONSTRAINT fk_SALARIES_Emp_No FOREIGN KEY(Emp_No)
REFERENCES EMPLOYEES (Emp_No);

ALTER TABLE TITLES ADD CONSTRAINT fk_TITLES_Emp_No FOREIGN KEY(Emp_No)
REFERENCES EMPLOYEES (Emp_No);

ALTER TABLE DEPT_MANAGER ADD CONSTRAINT fk_DEPT_MANAGER_Dept_No FOREIGN KEY(Dept_No)
REFERENCES DEPARTMENTS (Dept_No);

ALTER TABLE DEPT_MANAGER ADD CONSTRAINT fk_DEPT_MANAGER_Emp_No FOREIGN KEY(Emp_No)
REFERENCES EMPLOYEES (Emp_No);

ALTER TABLE DEPT_EMP ADD CONSTRAINT fk_DEPT_EMP_Emp_No FOREIGN KEY(Emp_No)
REFERENCES EMPLOYEES (Emp_No);

ALTER TABLE DEPT_EMP ADD CONSTRAINT fk_DEPT_EMP_Dept_No FOREIGN KEY(Dept_No)
REFERENCES DEPARTMENTS (Dept_No);

